In [1]:
import pandas as pd
import numpy as np

st_loc = pd.read_csv('station_coordinate.csv', encoding='utf8')
df = pd.read_csv('Total_Bicycle.csv', encoding='utf8')

In [3]:
df['대여일시']
df['대여일'] = df['대여일시'].str.split(" ", expand=True)[0]
df['대여시간'] = df['대여일시'].str.split(" ", expand=True)[1]
df['대여시간'] = df['대여시간'].str.split(":", expand=True)[0]

from datetime import datetime, date

def what_day(date):
    days = ['월', '화', '수', '목', '금', '토', '일']
    day = date.weekday()
    return days[day]
    
dday = []
for i in range(len(df)):
    qday = df['대여일'][i]
    datetime_date = datetime.strptime(qday, '%Y-%m-%d')
    qday = what_day(datetime_date)
    dday.append(qday)
df['대여요일'] = dday

df['반납일시']
df['반납일'] = df['반납일시'].str.split(" ", expand=True)[0]
df['반납시간'] = df['반납일시'].str.split(" ", expand=True)[1]
df['반납시간'] = df['반납시간'].str.split(":", expand=True)[0]
    
dday = []
for i in range(len(df)):
    qday = df['반납일'][i]
    datetime_date = datetime.strptime(qday, '%Y-%m-%d')
    qday = what_day(datetime_date)
    dday.append(qday)
df['반납요일'] = dday

df2 = df

In [5]:
df3 = df2[10000:10300] #예시용으로 300개만 읽게 함.
#df3 = df2
df3.reset_index(drop=True,inplace=True)

df_diff_rental = pd.DataFrame()
df_diff_return = pd.DataFrame()
station = []
diff_rental = []
diff_return = []
df3_rank1_station_rental = []
df3_rank1_diff_rental = []
df3_rank2_station_rental = []
df3_rank2_diff_rental = []
df3_rank1_station_return = []
df3_rank1_diff_return = []
df3_rank2_station_return = []
df3_rank2_diff_return = []
ex = pd.DataFrame()

for i in range(len(df3)):
    for j in range(len(st_loc)):
        station.append(st_loc['name'][j])
        diff_rental.append(np.sqrt((df3['대여소 위도'][i]-st_loc['lat'][j])**2 +
                            (df3['대여소 경도'][i]-st_loc['lng'][j])**2))
        diff_return.append(np.sqrt((df3['반납소 위도'][i]-st_loc['lat'][j])**2 +
                            (df3['반납소 경도'][i]-st_loc['lng'][j])**2))
    ex['역'] = station
    ex['대여'] = diff_rental
    ex['반납'] = diff_return
    df_diff_rental['역(대여)'] = station
    df_diff_return['역(반납)'] = station
    df_diff_rental['차이(대여)'] = diff_rental
    df_diff_return['차이(반납)'] = diff_return
    df_diff_rental.sort_values('차이(대여)', inplace=True)
    df3_rank1_station_rental.append(df_diff_rental.iloc[0]['역(대여)'])
    df3_rank1_diff_rental.append(df_diff_rental.iloc[0]['차이(대여)'])
    df3_rank2_station_rental.append(df_diff_rental.iloc[1]['역(대여)'])
    df3_rank2_diff_rental.append(df_diff_rental.iloc[1]['차이(대여)'])
    df_diff_return.sort_values('차이(반납)', inplace=True)
    df3_rank1_station_return.append(df_diff_return.iloc[0]['역(반납)'])
    df3_rank1_diff_return.append(df_diff_return.iloc[0]['차이(반납)'])
    df3_rank2_station_return.append(df_diff_return.iloc[1]['역(반납)'])
    df3_rank2_diff_return.append(df_diff_return.iloc[1]['차이(반납)'])
    station = []
    diff_rental = []
    diff_return = []
    
df3['1순위(대여)'] = df3_rank1_station_rental
df3['1순위 차이(대여)'] = df3_rank1_diff_rental
df3['2순위(대여)'] = df3_rank2_station_rental
df3['2순위 차이(대여)'] = df3_rank2_diff_rental
df3['1순위(반납)'] = df3_rank1_station_return
df3['1순위 차이(반납)'] = df3_rank1_diff_return
df3['2순위(반납)'] = df3_rank2_station_return
df3['2순위 차이(반납)'] = df3_rank2_diff_return
df3

C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['1순위(대여)'] = df3_rank1_station_rental
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['1순위 차이(대여)'] = df3_rank1_diff_rental
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['2순위(대여)'] = df3_rank2_station_rental
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['2순위 차이(대여)'] = df3_rank2_diff_rental
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['1순위(반납)'] = df3_rank1_station_return
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['1순위 차이(반납)'] = df3_rank1_diff_return
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['2순위(반납)'] = df3_rank2_station_return
C:\Users\smdhk\AppData\Local\Temp\ipykernel_17424\2443597484.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['2순위 차이(반납)'] = df3_rank2_diff_return

,Unnamed: 0,index,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,...,반납시간,반납요일,1순위(대여),1순위 차이(대여),2순위(대여),2순위 차이(대여),1순위(반납),1순위 차이(반납),2순위(반납),2순위 차이(반납)
0,10188,10223,SPB-38732,2022-06-18 18:13:07,103,망원역 2번출구 앞,0,2022-06-18 18:29:30,104,합정역 1번출구 앞,...,18,토,망원,0.001386,합정,0.006209,합정,0.001707,합정,0.001707
1,10189,10224,SPB-56282,2022-06-18 18:28:57,107,신한은행 서교동지점,0,2022-06-18 18:35:48,104,합정역 1번출구 앞,...,18,토,홍대입구,0.006886,홍대입구,0.006886,합정,0.001707,합정,0.001707
2,10190,10225,SPB-37864,2022-06-18 17:43:28,104,합정역 1번출구 앞,0,2022-06-18 18:41:15,104,합정역 1번출구 앞,...,18,토,합정,0.001707,합정,0.001707,합정,0.001707,합정,0.001707
3,10191,10226,SPB-62896,2022-06-18 18:38:28,106,합정역 7번출구 앞,0,2022-06-18 18:55:22,104,합정역 1번출구 앞,...,18,토,합정,0.001225,합정,0.001225,합정,0.001707,합정,0.001707
4,10192,10227,SPB-46565,2022-06-18 18:18:15,104,합정역 1번출구 앞,0,2022-06-18 19:01:01,104,합정역 1번출구 앞,...,19,토,합정,0.001707,합정,0.001707,합정,0.001707,합정,0.001707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,10483,10518,SPB-53693,2022-06-22 21:58:34,113,홍대입구역 2번출구 앞,0,2022-06-22 22:34:51,104,합정역 1번출구 앞,...,22,수,홍대입구,0.001580,홍대입구,0.001580,합정,0.001707,합정,0.001707
296,10484,10519,SPB-47665,2022-06-22 23:55:45,4217,한강공원 망원나들목,0,2022-06-23 00:10:14,104,합정역 1번출구 앞,...,00,목,마포구청,0.010231,망원,0.013173,합정,0.001707,합정,0.001707
297,10485,10520,SPB-61482,2022-06-23 00:10:03,4599,대림우성아파트 사거리,0,2022-06-23 01:02:31,104,합정역 1번출구 앞,...,01,목,대림,0.004867,대림,0.004867,합정,0.001707,합정,0.001707
298,10486,10521,SPB-59426,2022-06-23 01:25:12,3005,마포구청 청사내,0,2022-06-23 01:40:06,104,합정역 1번출구 앞,...,01,목,마포구청,0.002967,월드컵경기장,0.004373,합정,0.001707,합정,0.001707
299,10487,10522,SPB-50522,2022-06-23 01:48:02,4226,마포프레스티지자이 1,0,2022-06-23 02:06:10,104,합정역 1번출구 앞,...,02,목,이대,0.005248,대흥,0.005959,합정,0.001707,합정,0.001707

In [ ]:
# 몇몇 중복 역이 있음 ex) 2호선 합정, 6호선 합정, 나중에 라인까지 넣어주거나 중복을 제거해야할 것!

In [6]:
df3.to_csv('close_station_sample.csv', encoding='utf8')